// Custom Arsenal Preset
GRLIB_arsenal_weapons = [
//SPEARHEAD
	//Rifles
		"SPE_M1_Carbine",
		"SPE_M1_Garand",
		"SPE_M1903A3_Springfield",
	//Sniper Rifles
		"SPE_M1903A4_Springfield",
	//LMGs
		"SPE_M1918A2_BAR",
		"SPE_M1919A4",
		"SPE_M1919A6",
	//SMGs
		"SPE_M1A1_Thompson",
		"SPE_M3_GreaseGun",
		"SPE_Sten_Mk2",
		"SPE_Sten_Mk2_Suppressed",
	//Flame Throwers
		"SPE_M2_Flamethrower",
	//pistols
		"SPE_M1911",
	//Launchers
		"SPE_M1A1_Bazooka",
	//Crew Serve
		"SPE_M2_TRIPOD",
		"SPE_M1_81_BARREL",
		"SPE_M1_81_STAND",
//LIBERATION 1944
		"LIB_Colt_M1911",
		"LIB_FLARE_PISTOL", 
		"LIB_M1A1_Thompson",
		"LIB_M3_GreaseGun",
		"LIB_M1928_Thompson",
		"LIB_M1928A1_Thompson",
		"LIB_M1903A3_Springfield",
		"LIB_M1_Garand", 	
		"LIB_M1_Carbine",
		"LIB_M2_Flamethrower",
		"LIB_M1903A3_Springfield_Bayonet",
		"LIB_M1_Garand_Bayonet", 
		"LIB_M1_Garand_M7", 
		"LIB_M1A1_Carbine",
		"LIB_M1919A4", 	
		"LIB_M1918A2_BAR", 		
		"LIB_M1919A6",
		"LIB_M1903A4_Springfield",
		"LIB_M1A1_Bazooka",
		"LIB_FLARE_PISTOL", 
		"LIB_Webley_mk6",
		"LIB_Webley_Flare",
		"LIB_Welrod_mk1",
		"LIB_Sten_Mk2",
		"LIB_Sten_Mk5",
		"LIB_Sten_Mk5_Bayonet",
		"LIB_DELISLE",
		"LIB_LeeEnfield_No4",
		"LIB_PIAT_Rifle",
		"LIB_LeeEnfield_No4_Bayonet",
		"LIB_LeeEnfield_No4_CUP",	
		"LIB_LeeEnfield_No1",
		"LIB_LeeEnfield_No1_Bayonet",
		"LIB_LeeEnfield_No1_CUP",
		"LIB_Bren_Mk2",
		"LIB_LeeEnfield_No4_Scoped",
		"LIB_LeeEnfield_No4_Scoped_CUP",
		"LIB_PIAT",
		"LIB_M2_60_Barrel",
		"LIB_M2_60_Tripod",
		"LIB_M2_Tripod"
];

GRLIB_arsenal_magazines = [
//SPEARHEAD
	"SPE_8Rnd_9x19_P08",
	"SPE_32Rnd_9x19",
	"SPE_32rnd_9x19_t",
	"SPE_32Rnd_9x19_Sten",
	"SPE_5Rnd_792x57",
	"SPE_10Rnd_792x57",
	"SPE_30Rnd_792x33",
	"SPE_30rnd_792x33_t",
	"SPE_50Rnd_792x57",
	"SPE_100Rnd_792x57",
	"SPE_5Rnd_762x63",
	"SPE_5Rnd_762x63_t",
	"SPE_5Rnd_762x63_M1",
	"SPE_5Rnd_762x63_M2_AP",
	"SPE_8Rnd_762x63",
	"SPE_8Rnd_762x63_t",
	"SPE_8Rnd_762x63_M1",
	"SPE_8Rnd_762x63_M2_AP",
	"SPE_50Rnd_762x63",
	"SPE_100Rnd_762x63",
	"SPE_50Rnd_762x63_M1",
	"SPE_100Rnd_762x63_M1",
	"SPE_50Rnd_762x63_M2_AP",
	"SPE_100Rnd_762x63_M2_AP",
	"SPE_20Rnd_762x63",
	"SPE_20Rnd_762x63_M1",
	"SPE_20Rnd_762x63_M2_AP",
	"SPE_15Rnd_762x33",
	"SPE_15Rnd_762x33_t",
	"SPE_30Rnd_Thompson_45ACP",
	"SPE_20Rnd_Thompson_45ACP",
	"SPE_30Rnd_M3_GreaseGun_45ACP",
	"SPE_30Rnd_Thompson_45ACP_t",
	"SPE_20Rnd_Thompson_45ACP_t",
	"SPE_30Rnd_M3_GreaseGun_45ACP_t",
	"SPE_7Rnd_45ACP_1911",
	"SPE_25Rnd_75x54",
	"SPE_25Rnd_75x54_35P_AP",
	"SPE_2Rnd_12x65_Pellets",
	"SPE_2Rnd_12x65_Slug",
	"SPE_2Rnd_12x65_No4_Buck",
	"SPE_M2_Flamethrower_Mag",
	"SPE_Flammenwerfer41_Mag",
	"SPE_1Rnd_PzFaust_30m",
	"SPE_1Rnd_PzFaust_60m",
	"SPE_1Rnd_Faustpatrone",
	"SPE_1Rnd_60mm_M6",
	"SPE_Shg24",
	"SPE_Shg24_Frag",
	"SPE_Shg24x7",
	"SPE_M39",
	"SPE_US_Mk_2",
	"SPE_US_Mk_2_Yellow",
	"SPE_US_Mk_3",
	"SPE_US_M15",
	"SPE_US_AN_M14",
	"SPE_US_M18",
	"SPE_US_M18_Red",
	"SPE_US_M18_Green",
	"SPE_US_M18_Yellow",
	"SPE_US_M18_Violet",
	"SPE_US_Mk_1",
	"SPE_NB39",
	"SPE_NBK39b",
	"SPE_Handrauchzeichen_Red",
	"SPE_Handrauchzeichen_Violet",
	"SPE_Handrauchzeichen_Yellow",
	"SPE_Rauchsichtzeichen_Orange",
	"SPE_1Rnd_G_SPRGR_30",
	"SPE_1Rnd_G_PZGR_30",
	"SPE_1Rnd_G_PZGR_40",
	"SPE_1Rnd_G_NBGR_42",
	"SPE_1Rnd_G_FLGR",
	"SPE_1Rnd_G_Mk2",
	"SPE_1Rnd_G_M9A1",
	"SPE_1Rnd_G_M2_ANM8",
	"SPE_1Rnd_G_M2_M18_Red",
	"SPE_1Rnd_G_M2_M18_Yellow",
	"SPE_1Rnd_G_M2_M18_Green",
	"SPE_1Rnd_G_M2_M18_Violet",
	"SPE_1Rnd_G_M2_AN_M14",
	"SPE_1Rnd_G_M17A1",
	"SPE_1Rnd_G_M19A1",
	"SPE_1Rnd_G_M21A1",
	"SPE_1Rnd_G_M51A1",
	"SPE_5Rnd_792x57_t",
	"SPE_5Rnd_792x57_sS",
	"SPE_5Rnd_792x57_SMK",
	"SPE_10Rnd_792x57_T",
	"SPE_10Rnd_792x57_T2",
	"SPE_10Rnd_792x57_sS",
	"SPE_10Rnd_792x57_SMK",
	"SPE_50Rnd_792x57_sS",
	"SPE_100Rnd_792x57_sS",
	"SPE_50Rnd_792x57_SMK",
	"SPE_100Rnd_792x57_SMK",
	"SPE_Shg24x7_Improvised_Mine_mag",
	"SPE_TMI_42_MINE_mag",
	"SPE_SMI_35_1_MINE_mag",
	"SPE_SMI_35_MINE_mag",
	"SPE_SMI_35_Pressure_MINE_mag",
	"SPE_STMI_MINE_mag",
	"SPE_shumine_42_MINE_mag",
	"SPE_Ladung_Small_MINE_mag",
	"SPE_Ladung_Big_MINE_mag",
	"SPE_US_M1A1_ATMINE_mag",
	"SPE_US_M3_MINE_mag",
	"SPE_US_M3_Pressure_MINE_mag",
	"SPE_US_TNT_4pound_mag",
	"SPE_US_TNT_half_pound_mag",
	"SPE_US_Bangalore_mag",
	"SPE_24Rnd_SmokeLauncherMag",
	"SPE_3Rnd_GER_SmokeLauncherMag",
	"SPE_3Rnd_GER_LeftMineLauncherMag",
	"SPE_3Rnd_GER_RightMineLauncherMag",
	"SPE_FAKE_SHELL",
	"SPE_2000Rnd_MG131_FW190",
	"SPE_400Rnd_MG131",
	"SPE_500Rnd_MG151_FW190",
	"SPE_250Rnd_MG151",
	"SPE_800Rnd_M2",
	"SPE_4000Rnd_M2_P47",
	"SPE_425rnd_M2_P47",
	"SPE_1Rnd_SC50",
	"SPE_1Rnd_SC250",
	"SPE_1Rnd_US_500lb",
	"SPE_1Rnd_US_1000lb",
	"SPE_1Rnd_M47_WP",
	"SPE_1Rnd_SC500",
	"SPE_1Rnd_NC50",
	"SPE_1Rnd_NC250",
	"SPE_3Rnd_M8_P47",
	"SPE_8Rnd_81mmHE_M1_M43A1",
	"SPE_1Rnd_81mmHE_M1_M43A1",
	"SPE_8Rnd_81mm_FA_Mle_1932_HE",
	"SPE_1Rnd_81mm_FA_Mle_1932_HE",
	"SPE_8Rnd_81mmWP_M1_M57",
	"SPE_1Rnd_81mmWP_M1_M57",
	"SPE_8rnd_81mm_M1_M57_SmokeShell",
	"SPE_8Rnd_81mm_FA_Mle_1932_Smoke",
	"SPE_81mm_M1_M57_SmokeShell",
	"SPE_81mm_FA_Mle_1932_Smoke",
	"SPE_8Rnd_81mm_FA_Mle_1932_Illu",
	"SPE_81mm_FA_Mle_1932_Illu",
	"SPE_6Rnd_Wurfrahmen_40",
	"SPE_60Rnd_M8",
	"SPE_60Rnd_M8_direct",
	"SPE_20x_SprGr_FlaK_38",
	"SPE_20x_PzGr_FlaK_38_AP_T",
	"SPE_20x_SprGr_FlaK_30",
	"SPE_20x_PzGr_FlaK_30_AP_T",
	"SPE_M61_M1_AP",
	"SPE_M72_AP",
	"SPE_PzGr39_KWK40_AP",
	"SPE_40x_PzGr39_Pak40_AP",
	"SPE_12x_PzGr39_Pak40_AP",
	"SPE_PzGr43_AP",
	"SPE_PzGr39_KwK36_AP",
	"SPE_PzGr39_FLAK36_AP",
	"SPE_30x_PzGr39_FLAK36_AP",
	"SPE_6pdr_mk8_AP",
	"SPE_20x_6pdr_mk8_AP",
	"SPE_10x_6pdr_mk8_AP",
	"SPE_6pdr_mk9_APCBC",
	"SPE_20x_6pdr_mk9_APCBC",
	"SPE_57mm_M70_AP",
	"SPE_20x_57mm_M70_AP",
	"SPE_57mm_M86_APCBC",
	"SPE_20x_57mm_M86_APCBC",
	"SPE_76mm_M7_M62_APCBC",
	"SPE_76mm_M7_M79_AP",
	"SPE_76mm_M1_M62_APCBC",
	"SPE_76mm_M1_M79_AP",
	"SPE_76mm_M1_HC_M62_APCBC",
	"SPE_76mm_M1_HC_M79_AP",
	"SPE_105mm_LeFH_PzGrRot_AP",
	"SPE_20x_105mm_LeFH_PzGrRot_AP",
	"SPE_Shell_50L60_PzGr_AP",
	"SPE_Shell_50L42_PzGr_AP",
	"SPE_75mm_K51_KGrRotPz_AP",
	"SPE_15x_75mm_KGrRotPz_AP",
	"SPE_64x_75mm_KGrRotPz_AP",
	"SPE_T45_M1_APCR",
	"SPE_PzGr40_KWK40_APCR",
	"SPE_10x_PzGr40_Pak40_APCR",
	"SPE_6x_PzGr40_Pak40_APCR",
	"SPE_PzGr40_APCR",
	"SPE_PzGr40_KwK36_APCR",
	"SPE_PzGr40_FLAK36_APCR",
	"SPE_12x_PzGr40_FLAK36_APCR",
	"SPE_6pdr_Mk1T_APDS",
	"SPE_12x_6pdr_Mk1T_APDS",
	"SPE_76mm_M7_M93_APCR",
	"SPE_76mm_M1_M93_APCR",
	"SPE_76mm_M1_HC_M93_APCR",
	"SPE_Shell_50L60_PzGr40_APCR",
	"SPE_Shell_50L42_PzGr40_APCR",
	"SPE_M48_HE",
	"SPE_75mm_K51_SprGr34_HE",
	"SPE_SprGr34_KWK40_HE",
	"SPE_50x_SprGr34_Pak40_HE",
	"SPE_12x_SprGr34_Pak40_HE",
	"SPE_SprGr39_HE",
	"SPE_SprGr_KwK36_HE",
	"SPE_SprGr_FLAK36_HE",
	"SPE_21x_SprGr_FLAK36_HE",
	"SPE_SprGr_FLAK36_AA",
	"SPE_45x_SprGr_FLAK36_AA",
	"SPE_6pdr_mk10T_HE",
	"SPE_21x_6pdr_mk10T_HE",
	"SPE_15x_6pdr_mk10T_HE",
	"SPE_57mm_T18_HE",
	"SPE_21x_57mm_T18_HE",
	"SPE_76mm_M7_M42_HE",
	"SPE_76mm_M1_M42_HE",
	"SPE_76mm_M1_HC_M42_HE",
	"SPE_Shell_50L60_SprGr38_HE",
	"SPE_Shell_50L42_SprGr38_HE",
	"SPE_Shell_105L28_Gr38_HE",
	"SPE_20x_Shell_105L28_Gr38_HE",
	"SPE_20x_Shell_105L28_Gr38_HE_direct",
	"SPE_Shell_105L28_Gr39HlC_HEAT",
	"SPE_8x_Shell_105L28_Gr39HlC_HEAT",
	"SPE_8x_Shell_105L28_Gr39HlC_HEAT_Artillery",
	"SPE_75mm_K51_HLGr38c_HEAT",
	"SPE_M89_SMK",
	"SPE_KGrRotNB_KWK40_SMK",
	"SPE_5x_KGrRotNB_StuK40_SMK",
	"SPE_75mm_K51_KGrRotNB_SMK",
	"SPE_Shell_105L28_Gr38_NB",
	"SPE_20x_Shell_105L28_Gr38_NB",
	"SPE_20x_Shell_105L28_Gr38_NB_direct",
	"SPE_76mm_M7_M89_SMK",
	"SPE_76mm_M1_HC_M89_SMK",
	"SPE_1Rnd_US_Timed_Short_500lb",
	"SPE_1Rnd_US_Timed_Long_500lb",
	"SPE_1Rnd_US_Timed_Short_1000lb",
	"SPE_1Rnd_US_Timed_Long_1000lb",
	"SPE_1Rnd_Timed_Short_SC250",
	"SPE_1Rnd_Timed_Long_SC250",
	"SPE_1Rnd_Timed_Short_SC50",
	"SPE_1Rnd_Timed_Long_SC50",
	"SPE_1Rnd_Timed_Short_SC500",
	"SPE_1Rnd_Timed_Long_SC500",
//Crew Serve - maybe
	"8Rnd_81mmWP_M1_M57",
	"SPE_8rnd_81mm_M1_M57_SmokeShell",
	
	"LIB_7Rnd_45ACP", 	
	"LIB_1Rnd_flare_white", 	
	"LIB_1Rnd_flare_red", 	
	"LIB_1Rnd_flare_green", 	
	"LIB_1Rnd_flare_yellow",
	"LIB_30Rnd_45ACP", 	
	"LIB_30Rnd_45ACP_t", 	
	"LIB_30Rnd_M3_GreaseGun_45ACP", 		
	"LIB_50Rnd_45ACP",
	"LIB_5Rnd_762x63", 	
	"LIB_5Rnd_762x63_t",
	"LIB_8Rnd_762x63", 	
	"LIB_8Rnd_762x63_t", 	
	"LIB_15Rnd_762x33", 	
	"LIB_15Rnd_762x33_t", 	
	"LIB_1Rnd_145x114", 	
	"LIB_M2_Flamethrower_Mag", 	
	"LIB_M2_Flamethrower_Mag_Empty",
	"LIB_50Rnd_762x63", 	
	"LIB_20Rnd_762x63",
	"LIB_1Rnd_60mm_M6",
	"LIB_US_Mk_2",
	"LIB_US_M18", 	
	"LIB_US_M18_Red", 	
	"LIB_US_M18_Green", 	
	"LIB_US_M18_Yellow",
	"LIB_1Rnd_G_Mk2", 
	"LIB_1Rnd_G_M9A1",
	"LIB_US_M1A1_ATMINE_mag", 	
	"LIB_US_M3_MINE_mag", 	
	"LIB_US_TNT_4pound_mag",
	"LIB_6Rnd_455",
	"LIB_6Rnd_9x19_Welrod",
	"LIB_7Rnd_765x17",
	"LIB_1Rnd_flare_white", 	
	"LIB_1Rnd_flare_red", 	
	"LIB_1Rnd_flare_green", 	
	"LIB_1Rnd_flare_yellow",
	"LIB_32Rnd_9x19_Sten",
	"LIB_10Rnd_770x56", 	
	"LIB_1Rnd_89m_G_PIAT",
	"LIB_1Rnd_89m_PIAT",
	"LIB_30Rnd_770x56",
	"LIB_MillsBomb",
	"LIB_No82",
	"LIB_No77",
	"LIB_1Rnd_G_MillsBomb"
];

GRLIB_arsenal_items = [
    // Uniforms
	"U_SPE_US_Pilot",
	"U_SPE_US_Pilot_glove",
	"U_SPE_US_Pilot_boot",
	"U_SPE_US_Pilot_lthr",
	"U_SPE_US_Pilot_lthr_glove",
	"U_SPE_US_Pilot_lthr_boot",
	"U_SPE_US_S31A",
	"U_SPE_US_S31A_glove",
	"U_SPE_US_S31A_boot",
	"U_SPE_US_S31_erla",
	"U_SPE_US_S31_erla_glove",
	"U_SPE_US_S31_erla_boot",
	"U_SPE_US_Private",
	"U_SPE_US_Private_1st",
	"U_SPE_US_Corp",
	"U_SPE_US_Sergeant",
	"U_SPE_US_Technician",
	"U_SPE_US_Med",
	"U_SPE_US_Private_late",
	"U_SPE_US_Med_late",
	"U_SPE_US_HBT44",
	"U_SPE_US_HBT44_Med",
	"U_SPE_US_HBT44_trop",
	"U_SPE_US_HBT44_roll",
	"U_SPE_US_HBT44_late",
	"U_SPE_US_HBT44_late_roll",
	"U_SPE_US_HBT44_Half",
	"U_SPE_US_HBT44_FrogSkin_Jungle",
	"U_SPE_US_HBT44_FrogSkin_Jungle_Half",
	"U_SPE_US_HBT44_FrogSkin_Jungle_trop",
	"U_SPE_US_HBT44_FrogSkin_Jungle_roll",
	"U_SPE_US_CC_EM",
	"U_SPE_US_CC_EM_roll",
	"U_SPE_US_CC_EM_trop",
	"U_SPE_US_CC_EM_trop_roll",
	"U_SPE_US_CC_HBT_EM",
	"U_SPE_US_CC_HBT_EM_roll",
	"U_SPE_US_CC_HBT_EM_trop",
	"U_SPE_US_CC_HBT_EM_trop_roll",
	"U_SPE_US_CC_HBT_camo",
	"U_SPE_US_CC_HBT_camo_roll",
	"U_SPE_US_CC_HBT_camo_trop",
	"U_SPE_US_CC_HBT_camo_trop_roll",
	"U_SPE_US_CC_2LT",
	"U_SPE_US_CC_1LT",
	"U_SPE_US_CC_CPT",
	"U_SPE_US_Tank_Coverall",
	"U_SPE_US_Tank_Coverall_Trop",
	"U_SPE_US_Tank_Coverall_Legging",
	"U_SPE_US_Tank_Crew",
	"U_SPE_US_Tank_Crew2",
	"U_SPE_US_Tank_Crew3",
	"U_SPE_US_Tank_Crew4",
	"U_SPE_US_Tank_Crew_camo",
	"U_SPE_US_Tank_Crew_camo2",
	"U_SPE_US_Tank_Crew_medic",
	"U_SPE_US_Tank_Crew_medic_camo",
	"U_SPE_US_Rangers_Uniform",
	"U_SPE_US_Rangers_Private_1st",
	"U_SPE_US_Rangers_Corp",
	"U_SPE_US_Rangers_Sergeant",
	"U_SPE_US_Rangers_Technician",
	"U_SPE_US_Rangers_Med",
//UK
	"U_LIB_UK_DenisonSmock", 	
	"U_LIB_UK_P37", 	
	"U_LIB_UK_P37Jerkins", 	
	"U_LIB_UK_P37_LanceCorporal", 	
	"U_LIB_UK_P37Jerkins_LanceCorporal", 	
	"U_LIB_UK_P37_Corporal", 	
	"U_LIB_UK_P37Jerkins_Corporal", 	
	"U_LIB_UK_P37_Sergeant", 	
	"U_LIB_UK_P37Jerkins_Sergeant", 	
	"U_LIB_UK_KhakiDrills",
	"U_LIB_UK_P37_w", 	
	"U_LIB_UK_P37Jerkins_w", 	
	"U_LIB_UK_DenisonSmock_w",
//US
	"U_LIB_US_AB_Uniform_M42", 	
	"U_LIB_US_AB_Uniform_M42_Medic", 	
	"U_LIB_US_AB_Uniform_M42_506", 	
	"U_LIB_US_AB_Uniform_M42_Gas", 	
	"U_LIB_US_AB_Uniform_M42_FC", 	
	"U_LIB_US_AB_Uniform_M42_corporal", 	
	"U_LIB_US_AB_Uniform_M42_NCO", 	
	"U_LIB_US_AB_Uniform_M43", 	
	"U_LIB_US_AB_Uniform_M43_Medic", 	
	"U_LIB_US_AB_Uniform_M43_Flag", 	
	"U_LIB_US_AB_Uniform_M43_FC", 	
	"U_LIB_US_AB_Uniform_M43_corporal", 	
	"U_LIB_US_AB_Uniform_M43_NCO", 	
	"U_LIB_US_Pilot", 	
	"U_LIB_US_Pilot_2", 	
	"U_LIB_US_Bomber_Pilot", 	
	"U_LIB_US_Bomber_Crew", 	
	"U_LIB_US_Private", 	
	"U_LIB_US_Private_1st", 	
	"U_LIB_US_Corp", 	
	"U_LIB_US_Sergeant", 	
	"U_LIB_US_Eng", 	
	"U_LIB_US_Med", 	
	"U_LIB_US_Tank_Crew", 	
	"U_LIB_US_Tank_Crew2", 	
	"U_LIB_US_NAC_Uniform", 	
	"U_LIB_US_NAC_Uniform_2", 	
	"U_LIB_US_NAC_Med", 	
	"U_LIB_US_Rangers_Uniform", 	
	"U_LIB_US_Rangers_Private_1st", 	
	"U_LIB_US_Rangers_Corp", 	
	"U_LIB_US_Rangers_Sergeant", 	
	"U_LIB_US_Rangers_Eng", 	
	"U_LIB_US_Rangers_Med",

    // Headgear
	"H_SPE_US_Helmet_Pilot",
	"H_SPE_US_Helmet_Pilot_Op",
	"H_SPE_US_Helmet_Pilot_Glasses_Up",
	"H_SPE_US_Helmet_Pilot_Glasses_Down",
	"H_SPE_US_Helmet_Pilot_Respirator",
	"H_SPE_US_Helmet_Pilot_Respirator_Glasses_Up",
	"H_SPE_US_Helmet_Pilot_Respirator_Glasses_Down",
	"H_SPE_US_Helmet_Pilot_SWDG_Respirator",
	"H_SPE_US_Helmet_Pilot_SWDG_low_Respirator",
	"H_SPE_US_Helmet_H15",
	"H_SPE_US_Helmet_H15_Op",
	"H_SPE_US_Helmet_H15_SWDG",
	"H_SPE_US_Helmet_H15_SWDG_low",
	"H_SPE_US_Helmet_H15_O2",
	"H_SPE_US_Helmet_H15_B7_O2",
	"H_SPE_US_Helmet_H15_B7_low_O2",
	"H_SPE_US_Helmet_H15_SWDG_O2",
	"H_SPE_US_Helmet_H15_SWDG_low_O2",
	"H_SPE_US_Pilot_Cap",
	"H_SPE_US_Pilot_Cap_Khaki",
	"H_SPE_US_Helmet",
	"H_SPE_US_Helmet_ns",
	"H_SPE_US_Helmet_os",
	"H_SPE_US_Helmet_Net",
	"H_SPE_US_Helmet_Net_ns",
	"H_SPE_US_Helmet_Net_os",
	"H_SPE_US_Helmet_band",
	"H_SPE_US_Helmet_band_ns",
	"H_SPE_US_Helmet_band_os",
	"H_SPE_US_Helmet_band_net",
	"H_SPE_US_Helmet_band_net_ns",
	"H_SPE_US_Helmet_band_net_os",
	"H_SPE_US_Helmet_Scrim",
	"H_SPE_US_Helmet_Scrim_ns",
	"H_SPE_US_Helmet_Scrim_os",
	"H_SPE_US_Helmet_polar",
	"H_SPE_US_Helmet_polar_ns",
	"H_SPE_US_Helmet_polar_os",
	"H_SPE_US_Helmet_polar_net",
	"H_SPE_US_Helmet_polar_net_ns",
	"H_SPE_US_Helmet_polar_net_os",
	"H_SPE_US_Helmet_polar_Scrim",
	"H_SPE_US_Helmet_polar_Scrim_ns",
	"H_SPE_US_Helmet_polar_Scrim_os",
	"H_SPE_US_Helmet_Med",
	"H_SPE_US_Helmet_Med_ns",
	"H_SPE_US_Helmet_Med_os",
	"H_SPE_US_Helmet_Cap",
	"H_SPE_US_Helmet_CO",
	"H_SPE_US_Helmet_CO_Net",
	"H_SPE_US_Helmet_NCO",
	"H_SPE_US_Helmet_NCO_net",
	"H_SPE_US_Helmet_NCO_scrim",
	"H_SPE_US_Helmet_First_lieutenant",
	"H_SPE_US_Helmet_Second_lieutenant",
	"H_SPE_US_Helmet_29ID",
	"H_SPE_US_Helmet_29ID_ns",
	"H_SPE_US_Helmet_29ID_os",
	"H_SPE_US_Helmet_29ID_Net",
	"H_SPE_US_Helmet_29ID_Net_ns",
	"H_SPE_US_Helmet_29ID_Net_os",
	"H_SPE_US_Helmet_29ID_Scrim",
	"H_SPE_US_Helmet_29ID_Scrim_ns",
	"H_SPE_US_Helmet_29ID_Scrim_os",
	"H_SPE_US_Helmet_29ID_CO",
	"H_SPE_US_Helmet_29ID_NCO",
	"H_SPE_US_MP_Helmet_White",
	"H_SPE_US_MP_Helmet_White_ns",
	"H_SPE_US_MP_Helmet_White_os",
	"H_SPE_US_Helmet_Tank",
	"H_SPE_US_Helmet_Tank_M1_OS",
	"H_SPE_US_Helmet_Tank_M1_NS",
	"H_SPE_US_Helmet_Tank_M1_Scrim",
	"H_SPE_US_Helmet_Tank_polar",
	"H_SPE_US_Helmet_Tank_polar_tapes",
	"H_SPE_US_Helmet_Tank_polar_low",
	"H_SPE_US_Helmet_Tank_NG",
	"H_SPE_US_Helmet_Tank_tapes",
	"H_SPE_US_Helmet_Tank_Nun",
	"H_SPE_US_Rangers_Helmet",
	"H_SPE_US_Rangers_Helmet_ns",
	"H_SPE_US_Rangers_Helmet_os",
	"H_SPE_US_Rangers_Helmet_Cap",
	"H_SPE_US_Rangers_Helmet_First_lieutenant",
	"H_SPE_US_Rangers_Helmet_Second_lieutenant",
	"H_SPE_US_Rangers_Helmet_NCO",
//IFA3
	//UK
	"H_LIB_WP_Helmet", 	
	"H_LIB_WP_Helmet_camo", 	
	"H_LIB_WP_Helmet_med", 	
	"H_LIB_WP_Cap", 	
	"H_LIB_UK_Helmet_Mk2", 	
	"H_LIB_WP_Helmet_Mk2", 	
	"H_LIB_WP_Helmet_Mk2_Desert", 	
	"H_LIB_UK_Helmet_Mk2_FAK", 	
	"H_LIB_UK_Helmet_Mk2_Bowed", 	
	"H_LIB_WP_Helmet_Mk2_Bowed", 
	"H_LIB_WP_Helmet_Mk2_Desert_Bowed", 	
	"H_LIB_UK_Para_Helmet_Mk2", 	
	"H_LIB_WP_Para_Helmet_Mk2",
	"H_LIB_UK_Para_Helmet_Mk2_Net", 	
	"H_LIB_UK_Para_Helmet_Mk2_Camo", 	
	"H_LIB_UK_Para_Beret", 	
	"H_LIB_UK_Helmet_Mk2_Net", 	
	"H_LIB_UK_Helmet_Mk2_Camo", 	
	"H_LIB_UK_Helmet_Mk2_Beachgroup", 	
	"H_LIB_UK_Helmet_Mk2_FAK_Camo", 	
	"H_LIB_UK_Helmet_Mk2_Cover", 	
	"H_LIB_UK_Helmet_Mk3", 	
	"H_LIB_UK_Helmet_Mk3_Net", 	
	"H_LIB_UK_Helmet_Mk3_Camo", 	
	"H_LIB_UK_Pilot_Cap", 	
	"H_LIB_UK_Beret", 	
	"H_LIB_UK_Beret_Tankist", 
	"H_LIB_UK_Beret_Headset", 	
	"H_LIB_UK_Beret_Commando", 	
	"H_LIB_UK_Beret_Commando_Kieffer", 	
	"H_LIB_UK_Balmoral", 	
	"H_LIB_UK_Helmet_Mk2_Desert", 	
	"H_LIB_UK_Helmet_Mk2_Desert_Bowed",
	"H_LIB_UK_Helmet_Mk2_Cover_w", 	
	"H_LIB_UK_Helmet_Mk2_w", 	
	"H_LIB_UK_Helmet_Mk2_Net_w", 	
	"H_LIB_UK_Helmet_Mk3_w", 	
	"H_LIB_UK_Para_Helmet_Mk2_w", 	
	"H_LIB_UK_Para_Helmet_Mk2_Net_w",
	//US
	"H_LIB_US_AB_Helmet",
	"H_LIB_US_AB_Helmet_2", 	
	"H_LIB_US_AB_Helmet_3", 	
	"H_LIB_US_AB_Helmet_4", 	
	"H_LIB_US_AB_Helmet_5", 	
	"H_LIB_US_AB_Helmet_Jump_1", 	
	"H_LIB_US_AB_Helmet_Jump_2", 	
	"H_LIB_US_AB_Helmet_Clear_1", 	
	"H_LIB_US_AB_Helmet_Clear_2", 	
	"H_LIB_US_AB_Helmet_Clear_3", 	
	"H_LIB_US_AB_Helmet_Medic_1", 	
	"H_LIB_US_AB_Helmet_Plain_1", 	
	"H_LIB_US_AB_Helmet_Plain_2", 	
	"H_LIB_US_AB_Helmet_Plain_3", 	
	"H_LIB_US_AB_Helmet_NCO_1", 	
	"H_LIB_US_AB_Helmet_NCO_2", 	
	"H_LIB_US_AB_Helmet_CO_1", 	
	"H_LIB_US_AB_Helmet_CO_2", 	
	"H_LIB_US_Helmet_Pilot", 	
	"H_LIB_US_Helmet_Pilot_Glasses_Up", 	
	"H_LIB_US_Helmet_Pilot_Glasses_Down", 	
	"H_LIB_US_Helmet_Pilot_Respirator", 	
	"H_LIB_US_Helmet_Pilot_Respirator_Glasses_Up", 	
	"H_LIB_US_Helmet_Pilot_Respirator_Glasses_Down", 	
	"H_LIB_US_Pilot_Cap", 	
	"H_LIB_US_Pilot_Cap_Khaki", 	
	"H_LIB_US_Helmet", 	
	"H_LIB_US_Helmet_ns", 	
	"H_LIB_US_Helmet_os", 	
	"H_LIB_US_Helmet_Net", 	
	"H_LIB_US_Helmet_Net_ns", 	
	"H_LIB_US_Helmet_Net_os", 	
	"H_LIB_US_Helmet_Med", 	
	"H_LIB_US_Helmet_Med_ns", 	
	"H_LIB_US_Helmet_Med_os", 	
	"H_LIB_US_Helmet_Cap", 	
	"H_LIB_US_Helmet_CO", 	
	"H_LIB_US_Helmet_NCO", 	
	"H_LIB_US_Helmet_First_lieutenant", 	
	"H_LIB_US_Helmet_Second_lieutenant", 	
	"H_LIB_US_Helmet_Tank", 	
	"H_LIB_US_Rangers_Helmet", 	
	"H_LIB_US_Rangers_Helmet_ns", 	
	"H_LIB_US_Rangers_Helmet_os", 	
	"H_LIB_US_Rangers_Helmet_Cap", 	
	"H_LIB_US_Rangers_Helmet_First_lieutenant",
	"H_LIB_US_Rangers_Helmet_Second_lieutenant", 	
	"H_LIB_US_Rangers_Helmet_NCO",
	"H_LIB_US_Helmet_w", 	
	"H_LIB_US_Helmet_Cover_w", 	
	"H_LIB_US_Helmet_Net_w", 	
	"H_LIB_US_Helmet_Med_w", 	
	"H_LIB_US_Helmet_Cap_w", 	
	"H_LIB_US_Helmet_First_lieutenant_w", 	
	"H_LIB_US_Helmet_Second_lieutenant_w",

    // Facegear
	"SPE_None",
	"SPE_Cigarettes",
	"SPE_Glasses",
	"SPE_US_Glasses",
	"G_SPE_Cigar_Moza",
	"G_SPE_Cigarette_Belomorkanal",
	"G_SPE_Cigarette_Grundstein",
	"G_SPE_Cigarette_Strike_Outs",
	"G_SPE_Pipe_Sir_Winston",
	"G_SPE_Binoculars",
	"G_SPE_Ful_Vue",
	"G_SPE_Ful_Vue_Reinforced",
	"G_SPE_Sunglasses_US_Red",
	"G_SPE_Sunglasses_US_Yellow",
	"G_SPE_Polar_Goggles",
	"G_SPE_SWDG_Goggles",
	"G_LIB_Binoculars",
	"G_LIB_GER_Gloves4",
	"G_LIB_GER_Gloves5",
	"G_LIB_GER_Gloves3",
	"G_LIB_GER_Gloves2",
	"G_LIB_GER_Gloves1",
	"G_LIB_Headwrap",
	"G_LIB_Headwrap_gloves",
	"G_LIB_Mohawk",
	"G_LIB_Scarf2_B",
	"G_LIB_Scarf2_G",
	"G_LIB_Scarf_B",
	"G_LIB_Scarf_G",
	"G_LIB_Watch2",
	"G_LIB_Watch1",
	"LIB_GER_Gloves4",
	"LIB_GER_Gloves5",
	"LIB_GER_Gloves3",
	"LIB_GER_Gloves2",
	"LIB_GER_Gloves1",
	"LIB_Headwrap",
	"LIB_Headwrap_gloves",
	"LIB_Mohwak",	
	

    // Vests
	"V_SPE_US_LifeVest",
	"V_SPE_US_Vest_Bar",
	"V_SPE_US_Vest_Bar_assist",
	"V_SPE_US_Vest_M1919",
	"V_SPE_US_Vest_Asst_MG",
	"V_SPE_US_Vest_Carbine",
	"V_SPE_US_Vest_Carbine_eng",
	"V_SPE_US_Vest_Carbine_pick",
	"V_SPE_US_Vest_Carbine_mk2",
	"V_SPE_US_Vest_Carbine_m43",
	"V_SPE_US_Vest_Carbine_nco",
	"V_SPE_US_Vest_Carbine_nco_Radio",
	"V_SPE_US_Vest_Garand",
	"V_SPE_US_Vest_Garand_M43",
	"V_SPE_US_Vest_Garand_gp",
	"V_SPE_US_Vest_Garand_mk2",
	"V_SPE_US_Vest_Garand_eng",
	"V_SPE_US_Vest_Garand_45",
	"V_SPE_US_Vest_Garand_map",
	"V_SPE_US_Vest_Grenadier",
	"V_SPE_US_Vest_Medic",
	"V_SPE_US_Vest_Medic2",
	"V_SPE_US_Vest_Medic3",
	"V_SPE_US_Vest_Thompson",
	"V_SPE_US_Vest_Thompson_M43",
	"V_SPE_US_Vest_Thompson_nco",
	"V_SPE_US_Vest_Thompson_nco_Radio",
	"V_SPE_US_Vest_45",
	"V_SPE_US_Vest_45_off",
	"V_SPE_US_Assault_Vest",
	"V_SPE_US_Assault_Vest_alt",
	"V_SPE_US_Assault_Vest_Light",
	"V_SPE_US_Assault_Vest_eng",
	"V_SPE_US_Assault_Vest_rifle",
	"V_SPE_US_Assault_Vest_rifle_M43",
	"V_SPE_US_Assault_Vest_Bag",
	"V_SPE_US_Assault_Vest_dday",
	"V_SPE_US_Assault_Vest_dday_Bag",	
//UK
	"V_LIB_UK_P37_Rifleman", 	
	"V_LIB_UK_P37_Gasmask", 	
	"V_LIB_UK_P37_Sten", 	
	"V_LIB_UK_P37_Holster", 	
	"V_LIB_UK_P37_Heavy", 	
	"V_LIB_UK_P37_Officer", 	
	"V_LIB_UK_P37_Crew", 	
	"V_LIB_UK_P37_Rifleman_Blanco", 	
	"V_LIB_UK_P37_Gasmask_Blanco", 	
	"V_LIB_UK_P37_Sten_Blanco", 	
	"V_LIB_UK_P37_Holster_Blanco", 	
	"V_LIB_UK_P37_Heavy_Blanco", 	
	"V_LIB_UK_P37_Officer_Blanco ",
	"LIB_ACC_No4_Mk2_Bayo", 		
	"LIB_ACC_GL_Enfield_CUP_Empty", 
	"LIB_ACC_GL_DYAKONOV_Empty",
//US
	"V_LIB_US_AB_Vest_Bar", 	
	"V_LIB_US_AB_Vest_M1919", 	
	"V_LIB_US_AB_Vest_Asst_MG", 	
	"V_LIB_US_AB_Vest_Carbine", 	
	"V_LIB_US_AB_Vest_Carbine_eng", 	
	"V_LIB_US_AB_Vest_Carbine_nco", 	
	"V_LIB_US_AB_Vest_Carbine_nco_Radio", 	
	"V_LIB_US_AB_Vest_Garand", 	
	"V_LIB_US_AB_Vest_Grenadier", 	
	"V_LIB_US_AB_Vest_Thompson", 	
	"V_LIB_US_AB_Vest_Thompson_nco", 	
	"V_LIB_US_AB_Vest_Thompson_nco_Radio", 	
	"V_LIB_US_AB_Vest_45", 	
	"V_LIB_US_AB_Vest_Padded_Bar", 	
	"V_LIB_US_AB_Vest_Padded_M1919", 	
	"V_LIB_US_AB_Vest_Padded_Asst_MG", 	
	"V_LIB_US_AB_Vest_Padded_Carbine", 	
	"V_LIB_US_AB_Vest_Padded_Carbine_eng", 	
	"V_LIB_US_AB_Vest_Padded_Carbine_nco", 	
	"V_LIB_US_AB_Vest_Padded_Carbine_nco_Radio",	
	"V_LIB_US_AB_Vest_Padded_Garand", 	
	"V_LIB_US_AB_Vest_Padded_Grenadier", 	
	"V_LIB_US_AB_Vest_Padded_Thompson", 	
	"V_LIB_US_AB_Vest_Padded_Thompson_nco", 
	"V_LIB_US_AB_Vest_Padded_Thompson_nco_Radio", 	
	"V_LIB_US_AB_Vest_Padded_45", 	
	"V_LIB_US_LifeVest", 	
	"V_LIB_US_Vest_Bar", 	
	"V_LIB_US_Vest_M1919", 	
	"V_LIB_US_Vest_Asst_MG", 	
	"V_LIB_US_Vest_Carbine", 	
	"V_LIB_US_Vest_Carbine_eng", 	
	"V_LIB_US_Vest_Carbine_nco", 	
	"V_LIB_US_Vest_Carbine_nco_Radio", 	
	"V_LIB_US_Vest_Garand", 	
	"V_LIB_US_Vest_Grenadier", 	
	"V_LIB_US_Vest_Medic", 	
	"V_LIB_US_Vest_Medic2", 	
	"V_LIB_US_Vest_Thompson", 	
	"V_LIB_US_Vest_Thompson_nco", 	
	"V_LIB_US_Vest_Thompson_nco_Radio", 	
	"V_LIB_US_Vest_45", 	
	"V_LIB_US_Assault_Vest", 	
	"V_LIB_US_Assault_Vest_Light", 	
	"V_LIB_US_Assault_Vest_Thompson", 	
	"V_LIB_US_Assault_Vest_dday",
	
    // Items
    "SPE_M1918A2_BAR_Bipod",                                          // AT-4 Peep hole handler
    "SPE_ACC_M1_Bayo",                                              // M3 MAAWS sight
    "SPE_ACC_GL_M1",                                          // SMAW sight
    "SPE_ACC_M3_Suppressor_45acp",                                // AAC 762-SD
    "SPE_ACC_GL_M7",                              // AAC 762-SDN-6
    "SPE_ACC_GL_M8",                              // AAC 762-SDN-6
    "SPE_M1918A2_BAR_Handle",                              // AAC 762-SDN-6
	
    "lib_acc_gl_enfield_cup_empty",                                          // AT-4 Peep hole handler
    "lib_acc_gl_m7",                                              // M3 MAAWS sight
    "lib_acc_m1_bayo",                                          // SMAW sight
    "lib_acc_p1903_bayo",                                // AAC 762-SD
    "lib_acc_no4_mk2_bayo",                              // AAC 762-SDN-6
	
    "SPE_Binocular_US",                                                      // Map
	"LIB_Binocular_US",
    "LIB_Binocular_UK",                                                    // Radio
	
    // Vanilla Standard Items
    "SPE_US_FirstAidKit",                                                  // First Aid Kit
    "ItemMap",                                                      // Map
    "SPE_US_ItemWatch",                                                    // Watch
    "SPE_US_Medkit",                                                      // Medikit
    "SPE_US_ItemCompass",                                                      // Medikit
    "MineDetector",                                                 // Mine Detector
    "SPE_ToolKit"                                                     // Toolkit

	  // ACE Items
    "ACE_acc_pointer_green",                                        // Laser Pointer (green)
    "ACE_adenosine",                                                // Adenosine autoinjector
    "ACE_Altimeter",                                                // Altimeter Watch
    "ACE_artilleryTable",                                           // Artillery Rangetable
    "ACE_ATragMX",                                                  // ATragMX
    "ACE_Banana",                                                   // Banana
    "ACE_bloodIV_250",                                              // Blood IV (250 ml)
    "ACE_bloodIV_500",                                              // Blood IV (500 ml)
    "ACE_bloodIV",                                                  // Blood IV (1000 ml)
    "ACE_bodyBag",                                                  // Bodybag
    "ACE_CableTie",                                                 // Cable Tie
    "ACE_Cellphone",                                                // Cellphone
    "ACE_Chemlight_Shield",                                         // Chemlight Shield (Empty)
    "ACE_Clacker",                                                  // M57 Firing Device
    "ACE_DeadManSwitch",                                            // Dead Man's Switch
    "ACE_DefusalKit",                                               // Defusal Kit
    "ace_dragon_sight",                                             // SU-36/P Daysight
    "ACE_EarPlugs",                                                 // Earplugs
    "ACE_elasticBandage",                                           // Bandage (Elastic)
    "ACE_EntrenchingTool",                                          // Entrenching Tool
    "ACE_epinephrine",                                              // Epinephrine autoinjector
    "ACE_fieldDressing",                                            // Bandage (Basic)
    "ACE_Flashlight_KSF1",                                          // KSF-1
    "ACE_Flashlight_Maglite_ML300L",                                // Maglite ML300L
    "ACE_Flashlight_MX991",                                         // Fulton MX-991
    "ACE_Flashlight_XL50",                                          // Maglite XL50
    "ACE_HuntIR_monitor",                                           // HuntIR monitor
    "ACE_IR_Strobe_Item",                                           // IR Strobe
    "ACE_Kestrel4500",                                              // Kestrel 4500NV
    "ACE_M26_Clacker",                                              // M152 Firing Device
    "ACE_MapTools",                                                 // Map Tools
    "ACE_microDAGR",                                                // MicroDAGR GPS
    "ACE_morphine",                                                 // Morphine autoinjector
    "ACE_muzzle_mzls_338",                                          // Flash Suppressor (.338)
    "ACE_muzzle_mzls_93mmg",                                        // Flash Suppressor (9.3 mm)
    "ACE_muzzle_mzls_B",                                            // Flash Suppressor (7.62 mm)
    "ACE_muzzle_mzls_H",                                            // Flash Suppressor (6.5 mm)
    "ACE_muzzle_mzls_smg_01",                                       // FLash Suppressor (.45 ACP)
    "ACE_muzzle_mzls_smg_02",                                       // Flash Suppressor (9 mm)
    "ACE_MX2A",                                                     // MX-2A
    "ACE_NVG_Gen1",                                                 // NV Goggles (Gen1)
    "ACE_NVG_Gen2",                                                 // NV Goggles (Gen2)
    "ACE_NVG_Gen4",                                                 // NV Goggles (Gen4)
    "ACE_NVG_Wide",                                                 // NV Goggles (Wide)
    "ACE_packingBandage",                                           // Bandage (Packing)
    "ACE_personalAidKit",                                           // Personal Aid Kit
    "ACE_plasmaIV_250",                                             // Plasma IV (250 ml)
    "ACE_plasmaIV_500",                                             // Plasma IV (500 ml)
    "ACE_plasmaIV",                                                 // Plasma IV (1000 ml)
    "ACE_quikclot",                                                 // Bandage (QuickClot)
    "ACE_RangeCard",                                                // Range Card
    "ACE_RangeTable_82mm",                                          // 82 mm Rangetable
    "ACE_rope12",                                                   // Rope 12.2 meters
    "ACE_rope15",                                                   // Rope 15.2 meters
    "ACE_rope18",                                                   // Rope 18.3 meters
    "ACE_rope27",                                                   // Rope 27.4 meters
    "ACE_rope36",                                                   // Rope 36.6 meters
    "ACE_salineIV_250",                                             // Saline IV (250 ml)
    "ACE_salineIV_500",                                             // Saline IV (500 ml)
    "ACE_salineIV",                                                 // Saline IV (1000 ml)
    "ACE_Sandbag_empty",                                            // Sandbag (empty)
    "ACE_splint",                                                   // Splint
    "ACE_SpottingScope",                                            // Spotting Scope
    "ACE_SpraypaintBlack",                                          // Spray Paint (Black)
    "ACE_SpraypaintBlue",                                           // Spray Paint (Blue)
    "ACE_SpraypaintGreen",                                          // Spray Paint (Green)
    "ACE_SpraypaintRed",                                            // Spray Paint (Red)
    "ACE_surgicalKit",                                              // Surgical Kit
    "ACE_tourniquet",                                               // Tourniquet (CAT)
    "ACE_Tripod",                                                   // SSWT Kit
    "ACE_UAVBattery",                                               // UAV Battery
    "ACE_Vector",                                                   // Vector 21 Nite
    "ACE_VectorDay",                                                // Vector 21
    "ACE_VMH3",                                                     // VMH3
    "ACE_VMM3",                                                     // VMM3
    "ACE_wirecutter",                                               // Wirecutter
    "ACE_Yardage450",                                               // Yardage 450

    // ACRE Items
    "ACRE_PRC117F",                                                 // AN/PRC-117F
    "ACRE_PRC148",                                                  // AN/PRC-148
    "ACRE_PRC152",                                                  // AN/PRC-152
    "ACRE_PRC343",                                                  // AN/PRC-343
    "ACRE_PRC77",                                                   // AN/PRC-77
    "ACRE_SEM52SL",                                                 // SEM 52 SL
    "ACRE_SEM70",                                                   // SEM 70
    "ACRE_VHF30108",                                                // VHF30108 GSM
    "ACRE_VHF30108MAST",                                            // VHF30108 Mast
    "ACRE_VHF30108SPIKE",                                           // VHF30108 GS

];

GRLIB_arsenal_backpacks = [
    // Standard Vanilla Backpacks
	"B_SPE_CIV_musette",
	"B_SPE_CIV_satchel",
	"B_SPE_FFI_Gasbag",
	"B_SPE_US_Backpack",
	"B_SPE_US_Backpack_Bandoleer",
	"B_SPE_US_Backpack_dday",
	"B_SPE_US_Backpack_M43",
	"B_SPE_US_Backpack_M43_GP",
	"B_SPE_US_Backpack_Mk2",
	"B_SPE_US_Backpack_pick",
	"B_SPE_US_Backpack_RocketBag_Empty",
	"B_SPE_US_Backpack_roll",
	"B_SPE_US_Backpack_roll_gp",
	"B_SPE_US_Bandoleer",
	"B_SPE_US_Bandoleer_2",
	"B_SPE_US_Bandoleer_3",
	"B_SPE_US_GP_Bag",
	"B_SPE_US_M2Flamethrower",
	"B_SPE_US_M36",
	"B_SPE_US_M36_Bandoleer",
	"B_SPE_US_MGbag",
	"B_SPE_US_packboard_ammo",
	"B_SPE_US_packboard_eng",
	"B_SPE_US_packboard_mortar",
	"B_SPE_US_QAC",
	"B_SPE_US_Radio",
	"B_SPE_US_Radio_alt",
	"B_SPE_US_Radio_packboard",
	"B_SPE_US_Radio_packboard_light",
	"B_SPE_US_Respawn_Tent",
	"B_SPE_US_RocketBag_Empty",
	"B_SPE_US_Suspender",
	"B_SPE_US_Suspender_band",
	"B_SPE_US_Suspender_band_left",
	"B_SPE_US_Suspender_band_right",
	"B_SPE_US_Suspender_m43",
	"B_SPE_US_Suspender_m43_open",
	"B_SPE_US_Suspender_RocketBag",
	"B_SPE_US_TypeA3",
	
	// UK Backpacks
    "B_LIB_UK_HSack",                                                 // Kitbag (Green)
    "B_LIB_UK_HSack_Blanco",                                                 // Kitbag (Tan)
    "B_LIB_UK_HSack_Cape",                                                 // Kitbag (Green)
    "B_LIB_UK_HSack_Blanco_Cape",                                                 // Kitbag (Tan)
    "B_LIB_UK_HSack_Tea",                                                 // Kitbag (Green)
    "B_LIB_UK_HSack_Blanco_Tea",                                                 // Kitbag (Tan)
	"B_LIB_US_Bag", 	
	"LIB_Backpack_us", 	
	"B_LIB_US_BARBag",	
	"LIB_Backpack_US_BAR", 	
	"B_LIB_US_BazBag", 	
	"LIB_Backpack_US_Baz", 	
	"B_LIB_US_MineBag", 	
	"LIB_Backpack_US_Mine", 	
	"B_LIB_FunkBag", 	
	"FunkBag", 	
	"B_LIB_FunkBag_Empty", 	
	"B_LIB_RadioBag", 
	"RadioBag", 	
	"B_LIB_RadioBag_Empty", 	
	"LIB_Tripod_Bag", 	
	"LIB_M2_Tripod_Bag", 		
	"LIB_M2_60_Bag", 	
	"B_LIB_US_Radio",		
	"B_LIB_US_Radio_ACRE2",
	"B_LIB_US_M36", 	
	"B_LIB_US_M36_KOTH",
	"B_LIB_US_M36_Rope", 	
	"B_LIB_US_M36_Bandoleer", 	
	"B_LIB_US_Type5", 	
	"B_LIB_US_M36_Rocketbag", 	
	"B_LIB_US_M36_Rocketbag_Empty", 	
	"B_LIB_US_M36_Rocketbag_Big_Empty", 	
	"B_LIB_US_M36_MGbag", 	
	"B_LIB_US_TypeA3", 	
	"B_LIB_US_Backpack", 	
	"B_LIB_US_Backpack_dday",	
	"B_LIB_US_Backpack_Mk2", 	
	"B_LIB_US_Backpack_Bandoleer", 	
	"B_LIB_US_Backpack_eng", 	
	"B_LIB_US_MedicBackpack", 	
	"B_LIB_US_MedicBackpack_Empty", 	
	"B_LIB_US_MedicBackpack_Big_Empty", 	
	"B_LIB_US_Backpack_RocketBag", 	
	"B_LIB_US_Backpack_RocketBag_Empty", 	
	"B_LIB_US_Backpack_RocketBag_Big_Empty", 	
	"B_LIB_US_RocketBag", 	
	"B_LIB_US_RocketBag_Empty", 	
	"B_LIB_US_RocketBag_Big_Empty", 	
	"B_LIB_US_Radio_Empty", 	
	"B_LIB_US_Bandoleer", 	
	"B_LIB_US_MGbag", 
	"B_LIB_US_MGbag_Empty", 	
	"B_LIB_US_MGbag_Big_Empty", 	
	"B_LIB_US_M2Flamethrower",
	"B_LIB_SD_US_Army_LMG", 	
	"B_LIB_SD_US_Army_AR", 	
	"B_LIB_SD_US_Airborne_LMG",
	"LIB_M2_60_Tripod_Deployed"
];